### ISSUE TITLE
[Enhancement] More information about the cluster in the UI

### ISSUE THREAD

**Issue by PadmaB** [gardener/dashboard#64] opened 2018-04-20 13:12 UTC
While creating the cluster, the user provides multiple inputs:
1. Worker groups
2. Machine Type and other details

However, once the cluster is created, as a user, I miss finding the above details in the UI.
It will be handy to find these details in the UI in a user-presentable way rather than finding the details from the cluster yaml or from the node itself.

**Comment by vlerenc** [comment] 2018-04-20 13:16
Fully agreed, duplicate of #23.

**Closed by vlerenc** 2018-04-20 13:16 UTC
