### ISSUE TITLE
Misleading message on Shoot .metadata.name update 

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/dashboard#443] opened 2019-08-11 18:17 UTC
Steps to reproduce:
1. Navigate to the `<host>/namespace/<project-ns>/shoots/<shoot-name>/yaml`
2. Try to change `.metadata.name` of the Shoot and `Save`.
3. Ensure that the message is `Cluster specification has been successfully updated`

but

```
$ k edit shoot $SHOOT_NAME -n $NAMESPACE
error: shoots.garden.sapcloud.io "<new-name>" could not be found on the server
```

**Comment by grolu** [comment] 2019-08-13 15:02
The Gardener ApiServer does not return an error when you try to edit name, namespace etc. It simply ignores the new name as it is not allowed. We only show errors returned by the API Server. If the server does not return an error, we do not know about it.
I don't now why kubectl returns not found. Probably, because kubectl expects the resource to be located at the new location but as it is not renamed, kubectl returns not found.
This is just a guess. Please correct me if I'm wrong @holgerkoser @rfranzke

**Comment by holgerkoser** [comment] 2019-08-13 16:21
It is not possible to rename resources. kubectl returns not found because it tries to update the resource with the new name which does not exist.

**Comment by grolu** [comment] 2019-08-14 08:28
I will close this as this is expected behavior.

**Closed by grolu** 2019-08-14 08:28 UTC
