### ISSUE TITLE
No clusters in incognito mode

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#74] opened 2018-04-30 11:38 UTC
When I open the Dashboard in incognito mode, I see errors about the websocket connection in the log and get no clusters in the UI.

**Comment by petersutter** [comment] 2018-05-01 13:39
could you add a screenshot? I just checked it in incognito mode and it was working fine

**Comment by vlerenc** [comment] 2018-05-01 13:54
Just from afar (no VPN access right now), @holgerkoser saw it in a screen sharing session.

**Comment by grolu** [comment] 2018-05-14 07:26
Close this issue for now as we cannot reproduce the issue.

**Closed by grolu** 2018-05-14 07:26 UTC
Labels: bug
