### ISSUE TITLE
Healthy clusters shown when only broken ones should be shown

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#76] opened 2018-05-02 13:47 UTC
It seems, sometimes (flaky behavior) I see also healthy clusters, when only broken ones should be shown (down below only the OS cluster has issues, I clicked refresh again and again, so these are no clusters that were broken and now healthy):
<img width="1009" alt="screen shot 2018-05-02 at 15 46 08" src="https://user-images.githubusercontent.com/4974203/39526775-1adb32b6-4e20-11e8-819f-b8a593e0dd51.png">

**Comment by rfranzke** [comment] 2018-05-08 11:54
I've seen an issue with the readiness chips: If the technical status is `Unknown` then the dashboard shows them in the same color like when the status is `True` (healthy).

**Comment by vlerenc** [comment] 2018-05-08 12:28
Ah, so maybe my observation above was a consequence not of wrongly applied filters, but of an unknown status for the clusters, which were rendered as healthy?

**Comment by grolu** [comment] 2018-05-11 14:41
I added handling for the Unknown status: The tags now appear with a grey color. I also added some logic that fixes the issue that healthy clusters could show up in the unhealthy list when rapidly toggling the _Show only Shoots with Issues_ flag.
I close the issue for now. Please re-open it if the issue is not fixed.

**Closed by grolu** 2018-05-11 14:41 UTC
Labels: bug
