### ISSUE TITLE
Icons not loaded

### ISSUE THREAD

**Issue by rfranzke** [gardener/dashboard#441] opened 2019-08-02 05:59 UTC
Sometimes the dashboard icons are not loaded correctly:

![dashboard_icons1](https://user-images.githubusercontent.com/19169361/62347837-5e190600-b4fb-11e9-9343-30365115ca6a.png)

![dashboard_icons2](https://user-images.githubusercontent.com/19169361/62347839-5fe2c980-b4fb-11e9-8aec-370db04b9809.png)

**Comment by grolu** [comment] 2019-08-02 07:18
@holgerkoser I've never seen something like this. Did this ever occur to you?
@rfranzke Is this reproducible - does this happen from time to time or did this only occur once? What kind of browser did you use when it happened?

**Comment by rfranzke** [comment] 2019-08-02 07:28
Chrome. I don't know how to reproduce it, not easily at least. Refresh the dashboard multiple times, maybe you see it happen..

**Comment by petersutter** [comment] 2019-08-02 07:30
this should be addressed with https://github.com/gardener/dashboard/pull/439

**Comment by grolu** [comment] 2019-08-02 07:49
@petersutter Maybe, at least we do not rely on an external resource anymore. I guess in any case this is caused by network issues. The reason why only parts of the icons are not working is probably because we use different fonts. I will close the issue for now.

**Closed by grolu** 2019-08-02 07:49 UTC
Labels: area/usability, component/dashboard, kind/bug
