### ISSUE TITLE
Support use of OpenStack Application Credentials in the "Add new OpenStack Secret" dialog

### ISSUE THREAD

**Issue by berendt** [gardener/dashboard#1088] opened 2021-08-12 12:05 UTC
**What would you like to be added**:

The use of OpenStack Application Credentials in the "Add new OpenStack Secret" should be supported.

**Why is this needed**:

The Application Credentantials are already supported in the OpenStack extension and are the better solution to grant external systems access to an OpenStack environment. Therefore, it should also be possible to create secrets using application credentials in the UI.

**Comment by grolu** [comment] 2021-08-17 07:52
duplicate of #1049

**Closed by grolu** 2021-08-17 07:52 UTC
Labels: kind/enhancement, component/dashboard
