### ISSUE TITLE
Shoot detail doesn't show OIDC kubeconfig if OIDC is enabled

### ISSUE THREAD

**Issue by javamachr** [gardener/dashboard#999] opened 2021-04-19 12:17 UTC
**What would you like to be added**:
UI where one can see OIDC kubeconfig for endusers that would allow them to easily use it to access shoot.
**Why is this needed**:
Currently if OIDC is enabled for api server one has to create kubeconfig manually for endusers to let them use kubelogin with oidc.

**Comment by grolu** [comment] 2021-04-21 07:28
As @petersutter mentioned here: https://github.com/gardener/dashboard/pull/1000#issuecomment-822437482
Let's wait until Gardener exposes the feature.

**Comment by grolu** [comment] 2024-01-08 12:15
closed as this is a duplicate of #1596

**Closed by grolu** 2024-01-08 12:15 UTC
Labels: kind/enhancement, component/dashboard, status/external-action, lifecycle/rotten, status/blocked
